version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network-backend

  web:
    build: ./frontend
    depends_on:
      - api
    networks:
      - network-backend
    environment:
      REACT_APP_API_URL: http://34.172.78.49:80/api
    labels:
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.priority=1"
      - "traefik.http.middlewares.web-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.web.middlewares=web-strip-prefix"

  api:
    build: ./backend
    depends_on:
      - mongo
    networks: 
      - network-backend
    labels:
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.priority=2"

  mongo:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks: 
      - network-backend

networks:
  network-backend:
