version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network-backend

  web:
    build: ./frontend
    depends_on:
      - api
    networks:
      - network-backend
    environment:
      REACT_APP_API_URL: http://34.172.78.49:80/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.entrypoints=web"
  
  api:
    build: ./backend
    depends_on:
      - mongo
    networks: 
      - network-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
      - "traefik.http.routers.api.entrypoints=web"

  mongo:
    image: mongo
    restart: always
    networks: 
      - network-backend

networks:
  network-backend:
